return {
  -- {
  --   "echasnovski/mini.nvim",
  --   version = "*",
  --   lazy = false,
  -- },
  -- {
  --   "echasnovski/mini.files",
  --   version = "*",
  --   lazy = false,
  --   keys = {
  --     {
  --       "<leader>e",
  --       function()
  --         require("mini.files").open(vim.api.nvim_buf_get_name(0), true)
  --       end,
  --       desc = "Explorer mini.files (current dir)",
  --     },
  --     {
  --       "<leader>E",
  --       function()
  --         require("mini.files").open(vim.uv.cwd(), true)
  --       end,
  --       desc = "Explorer mini.files (cwd)",
  --     },
  --   },
  --   opts = {
  --     windows = {
  --       preview = true,
  --       width_focus = 40,
  --     },
  --     options = {
  --       use_as_default_explorer = true,
  --     },
  --     setup = {},
  --   },
  -- },
}
